/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.dsl.rhythm.serializer;

import com.google.inject.Inject;
import fr.polytech.dsl.rhythm.services.GuardinGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class GuardinSyntacticSequencer extends AbstractSyntacticSequencer {

	protected GuardinGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Music___PatternsKeyword_11_0_ColonKeyword_11_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (GuardinGrammarAccess) access;
		match_Music___PatternsKeyword_11_0_ColonKeyword_11_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getMusicAccess().getPatternsKeyword_11_0()), new TokenAlias(false, false, grammarAccess.getMusicAccess().getColonKeyword_11_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Music___PatternsKeyword_11_0_ColonKeyword_11_1__q.equals(syntax))
				emit_Music___PatternsKeyword_11_0_ColonKeyword_11_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('patterns' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     tracks+=Track (ambiguity) (rule end)
	 */
	protected void emit_Music___PatternsKeyword_11_0_ColonKeyword_11_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
