/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.dsl.rhythm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGuardinScopeProvider extends DelegatingScopeProvider {
}
