package fr.polytech.dsl.midi;

/**
	 * Partial list of Drum elements to ease the reading
	 */
	public enum DrumElement {
	ACOUSTIC_BASS_DRUM("ACOUSTIC_BASS_DRUM", 35), BASS_DRUM("BASS_DRUM", 36),
	SIDE_STICK("SIDE_STICK", 37), ACOUSTIC_SNARE("ACOUSTIC_SNARE", 38),
	HAND_CLAP("HAND_CLAP",39), ELECTRIC_SNARE("ELECTRIC_SNARE", 40),
	LO_FLOOR_TOM("LO_FLOOR_TOM", 41), CLOSED_HI_HAT("CLOSED_HI_HAT", 42),
	HIGH_FLOOR_TOM("HIGH_FLOOR_TOM", 43), PEDAL_HI_HAT("PEDAL_HI_HAT", 44),
	LO_TOM("LO_TOM", 45), OPEN_HI_HAT("OPEN_HI_HAT", 46), LO_MID_TOM("LO_MID_TOM",47),
	HI_MID_TOM("HI_MID_TOM", 48), CRASH_CYMBAL_1("CRASH_CYMBAL_1",49),
	HI_TOM("HI_TOM", 50), RIDE_CYMBAL_1("RIDE_CYMBAL_1", 51),
	CHINESE_CYMBAL("CHINESE_CYMBAL", 52), RIDE_BELL("RIDE_BELL", 53),
	TAMBOURINE("TAMBOURINE", 54), SPLASH_CYMBAL("SPLASH_CYMBAL", 55), COWBELL("COWBELL", 56),
	CRASH_CYMBAL_2("CRASH_CYMBAL_2", 57), VIBRASLAP("VIBRASLAP", 58),
	RIDE_CYMBAL_2("RIDE_CYMBAL_2", 59), HI_BONGO("HI_BONGO", 60), LO_BONGO("LO_BONGO", 61),
	MUTE_HI_CONGA("MUTE_HI_CONGA", 62), OPEN_HI_CONGA("OPEN_HI_CONGA", 63),
	LO_CONGA("LO_CONGA", 64), HI_TIMBALE("HI_TIMBALE", 65), LO_TIMBALE("LO_TIMBALE",66),
	HI_AGOGO("HI_AGOGO", 67), LO_AGOGO("LO_AGOGO", 68), CABASA("CABASA", 69), MARACAS("MARACAS", 70),
	SHORT_WHISTLE("SHORT_WHISTLE", 71), LONG_WHISTLE("LONG_WHISTLE", 72), SHORT_GUIRO("SHORT_GUIRO",73),
	LONG_GUIRO("LONG_GUIRO", 74), CLAVES("CLAVES", 75), HI_WOOD_BLOCK("HI_WOOD_BLOCK", 76), LO_WOOD_BLOCK("LO_WOOD_BLOCK", 77),
	MUTE_CUICA("MUTE_CUICA", 78), OPEN_CUICA("OPEN_CUICA", 79), MUTE_TRIANGLE("MUTE_TRIANGLE", 80), OPEN_TRIANGLE("OPEN_TRIANGLE", 81), SILENCE("R", -1);
		private String note;
		private int noteNumber;

	DrumElement(String note, int noteNumber) {
		this.note = note;
		this.noteNumber = noteNumber;
	}

	public String getNote() {
		return note;
	}

	public int getNoteNumber() {
		return noteNumber;
	}
}