/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.dsl.rhythm


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GuardinRuntimeModule extends AbstractGuardinRuntimeModule {
}
