/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.dsl.rhythm.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.polytech.dsl.rhythm.ide.contentassist.antlr.internal.InternalGuardinParser;
import fr.polytech.dsl.rhythm.services.GuardinGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GuardinParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GuardinGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GuardinGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getBatteryAccess().getNotesAlternatives_2_0(), "rule__Battery__NotesAlternatives_2_0");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getBatteryNoteTypeAccess().getAlternatives(), "rule__BatteryNoteType__Alternatives");
			builder.put(grammarAccess.getMusicAccess().getGroup(), "rule__Music__Group__0");
			builder.put(grammarAccess.getMusicAccess().getGroup_10(), "rule__Music__Group_10__0");
			builder.put(grammarAccess.getMusicAccess().getGroup_10_2(), "rule__Music__Group_10_2__0");
			builder.put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
			builder.put(grammarAccess.getTrackAccess().getGroup(), "rule__Track__Group__0");
			builder.put(grammarAccess.getTrackAccess().getGroup_1(), "rule__Track__Group_1__0");
			builder.put(grammarAccess.getBatteryAccess().getGroup(), "rule__Battery__Group__0");
			builder.put(grammarAccess.getBatteryAccess().getGroup_1(), "rule__Battery__Group_1__0");
			builder.put(grammarAccess.getEmptyNoteAccess().getGroup(), "rule__EmptyNote__Group__0");
			builder.put(grammarAccess.getBatteryNoteAccess().getGroup(), "rule__BatteryNote__Group__0");
			builder.put(grammarAccess.getMusicAccess().getNameAssignment_2(), "rule__Music__NameAssignment_2");
			builder.put(grammarAccess.getMusicAccess().getSectionsAssignment_6(), "rule__Music__SectionsAssignment_6");
			builder.put(grammarAccess.getMusicAccess().getSectionsAssignment_7(), "rule__Music__SectionsAssignment_7");
			builder.put(grammarAccess.getMusicAccess().getTracksAssignment_10_1(), "rule__Music__TracksAssignment_10_1");
			builder.put(grammarAccess.getMusicAccess().getTracksAssignment_10_2_1(), "rule__Music__TracksAssignment_10_2_1");
			builder.put(grammarAccess.getSectionAccess().getNameAssignment_1(), "rule__Section__NameAssignment_1");
			builder.put(grammarAccess.getSectionAccess().getTempoAssignment_4(), "rule__Section__TempoAssignment_4");
			builder.put(grammarAccess.getSectionAccess().getSignatureAssignment_6(), "rule__Section__SignatureAssignment_6");
			builder.put(grammarAccess.getSectionAccess().getBarsAssignment_8(), "rule__Section__BarsAssignment_8");
			builder.put(grammarAccess.getTrackAccess().getNameAssignment_1_0(), "rule__Track__NameAssignment_1_0");
			builder.put(grammarAccess.getTrackAccess().getInstrumentAssignment_4(), "rule__Track__InstrumentAssignment_4");
			builder.put(grammarAccess.getBatteryAccess().getNameAssignment_1_0(), "rule__Battery__NameAssignment_1_0");
			builder.put(grammarAccess.getBatteryAccess().getNotesAssignment_2(), "rule__Battery__NotesAssignment_2");
			builder.put(grammarAccess.getBatteryNoteAccess().getNoteTypeAssignment_1(), "rule__BatteryNote__NoteTypeAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GuardinGrammarAccess grammarAccess;

	@Override
	protected InternalGuardinParser createParser() {
		InternalGuardinParser result = new InternalGuardinParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GuardinGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuardinGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
